### ISSUE TITLE
Gene-level expression estimates

### ISSUE THREAD

**Issue by hooperj** [hartleys/JunctionSeq#16]
I need a single value for gene-level expression for each sample (or for each condition) that would be equivalent to the 'Read-pairs per sample, gene level' on the right side of the plots. Is there some place to find the values used in the plotting? Or a simple way of calculating them from values in the output tables?

In the 'sigGenes.expression.data' tables, all of the gene-level columns (by sample or by condition) have different numbers for each feature (exon/junction) of a given gene. I thought the counting strategy was just reads/gene, which should put the identical value for all features of a gene?!?!? Can you explain this for me?

And what should the units be on the base mean gene-level estimate (found in the sigGenes.genewiseResults). Read-pairs/gene/mean number of reads-sample???? How to transform that to Read-pairs/gene/million reads, or something similar to the more familiar fpkm or rpkm units?

**Comment by hartleys** [comment]
For each "feature" (exon or junction), JunctionSeq tests for a differential in the specific feature versus the "rest of the gene". So we take the exon/feature counts for the "rawCounts" bins, and the gene-level counts minus the exon/junction counts to get the "rawGeneCounts" bin. Add them together and you get the normal gene counts. See section 7.1 and 7.2 in the JunctionSeq manual for more detail.

For example, in the "sigGenes.expression.data" tables, the column "rawCounts_SAMP1" and "rawGeneCounts_SAMP1" will add up to the same number for all the features on a given gene. For example, in the [example dataset](https://dl.dropboxusercontent.com/u/103621176/pipelineWalkthrough/QoRTsPipelineWalkthrough.zip), these columns add up to 3337 for the first gene in the table.

The "expr_CASE" and "geneExpr_CASE" are extracted from the generalized linear model estimates, and thus they will usually add up to almost the same number in each row, but there will be a small amount of variation caused by the model fit and estimation process.

You can access the gene-level raw counts via the command:

    jscs@geneCountData

And you can access the phenotype gene-level estimates (the values plotted on the right in the expression plots) using the command:

    jscs@geneLevelPlottingEstimates$geneLevelEstModeled

But if you are only interested in gene-level effects and aren't actually looking for differential splicing, then you might want to actually just use DESeq2 or edgeR, which will give you better gene level estimates (since they aren't trying to model exons/junctions). 

Does that answer your questions?

**Comment by hooperj** [comment]
Perfect!
We wanted to stratify our DU events by mean gene-level expression and by gene-level fold-change between conditions. So we wanted a consensus gene-level expression value for each gene in each sample/condition.

The last question was units to attach to those gene-level estimates, which I assume would be normalized read-pairs/gene (where it is normalized to the size factors calculated in QoRTs). In which case I could convert to a standard unit, read-pairs/gene/million reads (RPM), by dividing by the mean read depth across all samples?

**Comment by hartleys** [comment]
Yes, the units are "normalized read-pair counts".

And yes: when people want RPM units, I just divide by the mean read depth (in millions).
