### ISSUE TITLE
Required features in GTF file.

### ISSUE THREAD

**Issue by brgew** [hartleys/JunctionSeq#21]
26 April 2017

Hi,

I wonder what feature types are required in the GTF file used by QoRTs, only 'exon's, as for DEXSeq,
or are others required?

Thank you for these programs!

**Comment by hartleys** [comment]
The exon lines are the most important by far. There are a few things that are needed by one or two specific metrics, but that are not needed in order for QoRTs to run. 

Specifically:

* In order to generate the UTR vs coding metrics, you will also need the "CDS" lines.
* In order to calculate the "biotype" metrics, you'll obviously need the biotype optional tags.

QoRTs ignores all lines other than "CDS" and "exon".
