### ISSUE TITLE
Issues dealing with large aggregated gene clusters

### ISSUE THREAD

**Issue by warrenmcg** [hartleys/JunctionSeq#7]
Hi Steve,

I was able to rerun the analysis successfully with your troubleshooting, and here are two related issues I'm facing with aggregated gene clusters identified as significant:
1) The "geneID" column main gene table on the results HTML page gets unwieldy as the clusters get larger than 3 or 4. Is it possible to wrap the "geneID column" if it gets beyond a certain size?
2) I actually had the "buildAllPlots" step fail with one of the clusters (41 members) as too large to create the gene expr.plot.html. I realize this is an extreme edge case, but is it possible to have these gene html pages use the simpler number format (or at least for gene clusters that exceed the longest file size allowable, which is 255 characters on linux systems)? An example change would be "geneID1-cluster".

Best,
Warren

**Comment by hartleys** [comment]
Hmm. Yes, that is both annoying and easily fixed. I will work out a fix and
include it in the next release, hopefully early next week.

By the way, I do recommend you be really careful when running with
use.multigene.aggregates = TRUE.

A lot of the assumptions may get broken when this is active, and these
multi gene aggregates often show up as false discoveries in tissues that
have a lot of gene-level DE going on.

And, because of the way the (standard) FDR p-adjust works, including a
bunch of genes that show a disproportionate amount of false significance
can actually inflate significance for the rest of your tests.

So be careful, is all.

**Comment by warrenmcg** [comment]
I added an idea about how to handle the first issue to my pull request (#6) after doing some googling. 

I modified the default css file to include a "wrapping" class for td elements. I then labeled both the geneID and name columns with this class. Finally, I inserted an zero-width space (html code 8203) to signal to the algorithm doing the auto-formatting that the "+" are breakable.

What are you thinking for handling the second issue? I would like to solve this as soon as possible so I can show my boss some of the visualizations (hopefully by Monday) in anticipation of a paper we're writing, so I'm willing to help contribute the necessary code to make it happen.

**Comment by hartleys** [comment]
elegant solution to (1). I like it.

For 2, i was going to shorten the names in the files by using a "..." when
there are more than 2-3 genes.

But I probably wont get a chance to post a proper release in time for
monday due to the testing regimen that I subject all updates to.

You can always pass an explicit gene list to buildAllPlots, and just leave
out the 40-gene aggregate. I think the parameter is "gene.list".

**Comment by warrenmcg** [comment]
Thanks! Rigorous testing is fine with me! For now, I'll do what you suggested with the gene.list, and then I'll see what I can do about the large aggregates (hopefully that's the only one...).

**Comment by hartleys** [comment]
The newest update fixes the above issues. I also added more tests to the test suite to make sure they work properly.

Thanks for pointing this out!

Let me know if you still have problems.
