### ISSUE TITLE
Help in interpreting differential usage of exon in a gene that has only 1 isoform

### ISSUE THREAD

**Issue by dnrichardson** [hartleys/JunctionSeq#9]
Hello!

Thanks very much for the effort in developing QoRTs and JunctionSeq. I'm very enthusiastic about the results I've obtained and will shortly validate some of the output via qRT-PCR. However, I do have a question that I've had some difficulty in trying to answer on my own and it pertains to single isoform genes. I have several cases (8 out of 22 total sig genes) that _have only a single isoform_ but display differential usage of an exon or junction in that isoform. Please see the attached image for a prominent example. 

**Single Isoform Gene with differential usage of E001**
![21-rexpr-tx](https://cloud.githubusercontent.com/assets/10101668/15212601/978ae4c4-1839-11e6-8df1-ad17b95be3b9.png)

Have you seen such cases before in your experience? It seems obvious that there is differential usage of the exon across conditions, yet since it arises from the same isoform, I am bit stumped as how to interpret it. Do cases like these suggest that perhaps other transcription/post-transcriptional events are at play in increasing the usage of this particular exon? 

In a related question, what can one do in terms of validation in cases where differential usage of the same exon is detected in 3 isoforms (please see the second figure below)? It's my understanding that in these cases, it is not possible to determine which isoform is specifically differentially regulated, only that there is evidence for alternative isoform regulation. Would you agree?

**Gene with 3 isoforms but differential usage of E007**
![01-rexpr-tx](https://cloud.githubusercontent.com/assets/10101668/15212876/47e9a3ae-183b-11e6-9b83-902a413c7bad.png)

I appreciate any feedback you may have.. 

Thank you for your time and consideration.

Best,
Dale

**Comment by hartleys** [comment]
First off: just because there is only one known isoform doesn't mean there's actually only one isoform. One of the benefits of using JunctionSeq is that it can detect differential usage even when the relevant isoforms are unannotated (as long as the exons are known). Even our best annotations are fairly incomplete.

But your example cases are very, very strange. I don't understand how it's possible for the gene-level counts and the exon-level counts to be so different when there is only one covered exon. It kind of looks like it might just be a counting artifact.

What species is this? Have you added novel splice junctions?

**Comment by dnrichardson** [comment]
Thank you for the reply. Regarding the presence of unannotated isoforms, yes, you're absolutely right. 

Regarding the first example case, I'm including a screen shot of the table view below. Should cases like this be simply disregarded from further consideration? 

The species is Arabidopsis and I have included novel splice junctions in the analysis. 

Thank you for the help..

<img width="1245" alt="screen shot 2016-05-18 at 22 14 50" src="https://cloud.githubusercontent.com/assets/10101668/15375342/783cf0a0-1d46-11e6-8528-245fa4e74427.png">

**Comment by hartleys** [comment]
In general I find the "relative coverage" plot to be less useful for figuring out what is going on, since the values are adjusted by the gene-level coverage.

For figuring out things like this, I prefer the "NormCounts" plot, since it includes the most information.

The [IGV](https://www.broadinstitute.org/igv/) genome browser supports the Aribidopsis genome. I suggest you load the data into that browser and look at it directly. You can either load the bam files directly (if they are sorted and indexed), or load the wiggle/bed files generated by QoRTs. I would also recommend loading the "orphanSplices.gff.gz" file generated by QoRTs when you merged novel splices. This will point out any oddball splice junctions that might be related but that QoRTs couldn't link to the gene.

So that's where I'd look next if I wanted to explore this gene further. The wiggle plot will show you where the reads are appearing, which will hopefully explain what is going on.

But as I said before: most likely it's just an artifact. It could be produced by repetitive sequence or similar mapping artifacts, or maybe just the fact that the Arabidopsis genome is fairly incomplete. It doesn't particularly look like real differential splicing.

**Comment by dnrichardson** [comment]
Thank you. Looking at the NormCounts plot reveals that one of the two replicates for my Wildtype looks to be what is driving the observed difference. Looks like this is probably a counting artefact as you suggested. In fact, I have quite a few cases that look similar: one of the replicates deviates prominently from its companion. A shame that we were unable to run this experiment with triplicates. I loaded up the Orphan Splices GFF into IGV along with the bams, but there were no  junctions associated with this gene. 

Well, it looks like I’ll be relying on the normalized counts and weed out any cases similar to this one. 

Thank you again for the helpful suggestions!

![21-normcts-tx](https://cloud.githubusercontent.com/assets/10101668/15515533/8879a39c-21e6-11e6-97d6-8029769a97fb.png)
